name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_call:

jobs:
  run:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      fail-fast: true
    
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          check-latest: true
      
      - name: Go Format
        run: gofmt -s -w . && git diff --exit-code
      
      - name: Go Vet
        run: go vet ./...
      
      - name: Go Tidy
        run: go mod tidy && git diff --exit-code
      
      - name: Go Mod
        run: go mod download
      
      - name: Go Mod Verify
        run: go mod verify
      
      - name: Go Build
        run: go build -o /dev/null ./...
      
      - name: Go Compile Tests
        run: go test -exec /bin/true ./...
      
      - name: Go Test
        run: go test -v -count=3 -race -shuffle=on -coverprofile=./cover.out -covermode=atomic -coverpkg=./... ./...
      
      - name: Static Analysis
        uses: dominikh/staticcheck-action@v1
        with:
          version: "latest"
          install-go: false

      - name: Check test coverage
        uses: vladopajic/go-test-coverage@v2
        with:
          config: ./.testcoverage.yml